-- ==========================================
-- BACKUP DE SCHEMA - JUNTA MÉDICA KLINI
-- DATA: 2026-02-04
-- ==========================================

-- 1. ESTRUTURA BASE (Projetos e Gerenciamento)
-- ==========================================
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  status text check (status in ('pending', 'progress', 'done', 'blocked')) default 'pending',
  priority text check (priority in ('low', 'medium', 'high')) default 'medium',
  deadline date
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references public.projects(id) on delete cascade not null,
  title text not null,
  status text check (status in ('pending', 'done')) default 'pending',
  completed_at date
);

-- 2. MÓDULO MÉDICO (Tabelas Principais)
-- ==========================================
create table if not exists public.medical_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  requisicao text unique not null,
  ben_nome text not null,
  ben_cpf text not null,
  ben_email text,
  ben_sexo text,
  ben_nascimento date,
  ben_telefone text,
  ben_estado text,
  ben_cidade text,
  aud_nome text not null,
  aud_estado text,
  aud_crm text not null,
  aud_data date,
  ass_nome text not null,
  ass_crm text not null,
  ass_email text,
  ass_telefone text,
  ass_endereco text,
  ass_especialidade text,
  div_especialidade text,
  div_motivos text[],
  situacao text not null default 'Aguardando Análise',
  prazo_ans date,
  documentos_internos jsonb default '{
    "aberturaBeneficiario": [],
    "aberturaFechamentoMedica": [],
    "desempatador": [],
    "parecerFinal": [],
    "emailConfirmacaoMedico": [],
    "beneficiarioAberturaFechamento": [],
    "confirmacaoRecebimento": []
  }'::jsonb,
  desempatador_nome text,
  desempatador_crm text,
  desempatador_especialidade text,
  desempate_ass_nome text,
  desempate_ass_crm text,
  desempate_ass_especialidade text,
  parecer_conclusao text
);

create table if not exists public.medical_procedures (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  codigo text,
  descricao text not null,
  qtd_solicitada integer default 1,
  qtd_autorizada integer default 0,
  justificativa text,
  conclusao_desempate TEXT
);

create table if not exists public.medical_materials (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  descricao text not null,
  qtd_solicitada integer default 1,
  qtd_autorizada integer default 0,
  justificativa text,
  conclusao_desempate TEXT
);

create table if not exists public.medical_attachments (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  file_name text not null,
  file_path text not null,
  created_at timestamp with time zone default now()
);

-- 3. PERFIS E PERMISSÕES (Auth Context)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  is_approved BOOLEAN DEFAULT false,
  access_projects BOOLEAN DEFAULT false,
  access_rooms BOOLEAN DEFAULT false,
  access_audit BOOLEAN DEFAULT false,
  access_medical boolean default false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.medical_requests enable row level security;
alter table public.medical_procedures enable row level security;
alter table public.medical_materials enable row level security;
alter table public.medical_attachments enable row level security;
alter table public.profiles enable row level security;
