-- MASTER MIGRATION SCRIPT - Hub Manager
-- Execute this on the new Supabase project's SQL Editor

-- 0. Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  is_approved BOOLEAN DEFAULT false,
  access_projects BOOLEAN DEFAULT false,
  access_rooms BOOLEAN DEFAULT false,
  access_audit BOOLEAN DEFAULT false,
  access_medical BOOLEAN DEFAULT false,
  cpf TEXT,
  birth_date DATE,
  setor TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Projects & Tasks
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  status text check (status in ('pending', 'progress', 'done', 'blocked')) default 'pending',
  priority text check (priority in ('low', 'medium', 'high')) default 'medium',
  deadline date,
  diagram_code text -- For DevCockpit
);

CREATE TABLE IF NOT EXISTS public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references public.projects(id) on delete cascade not null,
  title text not null,
  status text check (status in ('pending', 'done', 'progress', 'blocked')) default 'pending',
  position integer default 0,
  start_date date,
  deadline date,
  completed_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.subtasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  task_id bigint references public.tasks(id) on delete cascade not null,
  title text not null,
  status text check (status in ('pending', 'done')) default 'pending',
  assignee text,
  position integer default 0,
  completed_at timestamp with time zone
);

-- 3. Room Bookings
CREATE TABLE IF NOT EXISTS public.room_bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  start_time time not null,
  end_time time not null,
  title text not null,
  sector text,
  description text
);

-- 4. Medical Regulation Module
CREATE TABLE IF NOT EXISTS public.medical_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  requisicao text unique not null,
  ben_nome text not null,
  ben_cpf text not null,
  ben_email text,
  ben_sexo text,
  ben_nascimento date,
  ben_telefone text,
  ben_estado text,
  ben_cidade text,
  aud_nome text not null,
  aud_estado text,
  aud_crm text not null,
  aud_data date,
  ass_nome text not null,
  ass_crm text not null,
  ass_email text,
  ass_telefone text,
  ass_endereco text,
  ass_especialidade text,
  div_especialidade text,
  div_motivos text[],
  situacao text not null default 'Aguardando Análise',
  prazo_ans date,
  documentos_internos jsonb,
  -- Tiebreaker fields
  desempatador_nome text,
  desempatador_crm text,
  desempatador_especialidade text,
  desempate_ass_nome text,
  desempate_ass_crm text,
  desempate_ass_especialidade text,
  parecer_conclusao text,
  referencias_bibliograficas text,
  tiebreaker_token text unique,
  tiebreaker_allow_edit boolean default false,
  tiebreaker_verify_crm text,
  tiebreaker_verify_cpf text
);

CREATE TABLE IF NOT EXISTS public.medical_procedures (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  codigo text,
  descricao text not null,
  qtd_solicitada integer default 1,
  qtd_autorizada integer default 0,
  justificativa text,
  conclusao_desempate text
);

CREATE TABLE IF NOT EXISTS public.medical_materials (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  descricao text not null,
  qtd_solicitada integer default 1,
  qtd_autorizada integer default 0,
  justificativa text,
  conclusao_desempate text
);

CREATE TABLE IF NOT EXISTS public.medical_attachments (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  file_name text not null,
  file_path text not null,
  created_at timestamp with time zone default now()
);

-- 5. Audit Logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users,
  user_email TEXT,
  action TEXT NOT NULL,
  table_name TEXT NOT NULL,
  record_id TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB
);

-- 6. Functions & Logic
-- Signup Handler
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, is_approved)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', false);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Password Reset (Advanced)
CREATE OR REPLACE FUNCTION admin_reset_password_via_validation(
    email_input TEXT,
    cpf_input TEXT,
    birth_date_input DATE,
    new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
    target_user_id UUID;
BEGIN
    SELECT id INTO target_user_id FROM public.profiles
    WHERE email = email_input AND cpf = cpf_input AND birth_date = birth_date_input;

    IF target_user_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Dados incorretos.');
    END IF;

    UPDATE auth.users SET encrypted_password = crypt(new_password, gen_salt('bf'))
    WHERE id = target_user_id;

    RETURN jsonb_build_object('success', true, 'message', 'Sucesso!');
END;
$$;

-- Global Audit Function
CREATE OR REPLACE FUNCTION process_audit_log()
RETURNS TRIGGER AS $$
DECLARE
  current_user_id UUID;
  current_user_email TEXT;
BEGIN
  current_user_id := auth.uid();
  SELECT email INTO current_user_email FROM auth.users WHERE id = current_user_id;

  INSERT INTO public.audit_logs (
    user_id, user_email, action, table_name, record_id, old_data, new_data
  ) VALUES (
    current_user_id, current_user_email, TG_OP, TG_TABLE_NAME, 
    CASE WHEN TG_OP = 'DELETE' THEN OLD.id::text ELSE NEW.id::text END,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END
  );
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Triggers
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Audit Triggers for main tables
DROP TRIGGER IF EXISTS tr_audit_projects ON public.projects;
CREATE TRIGGER tr_audit_projects AFTER INSERT OR UPDATE OR DELETE ON public.projects FOR EACH ROW EXECUTE FUNCTION process_audit_log();

DROP TRIGGER IF EXISTS tr_audit_medical_requests ON public.medical_requests;
CREATE TRIGGER tr_audit_medical_requests AFTER INSERT OR UPDATE OR DELETE ON public.medical_requests FOR EACH ROW EXECUTE FUNCTION process_audit_log();

-- 8. Row Level Security Policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subtasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Simple "Allow All for Admin" and "Restricted for Users" pattern
-- (Add more specific policies here based on needs)

CREATE POLICY "Profiles viewable by all" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Profiles updateable by owner" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Projects access" ON public.projects FOR ALL USING (true);
CREATE POLICY "Tasks access" ON public.tasks FOR ALL USING (true);
CREATE POLICY "Subtasks access" ON public.subtasks FOR ALL USING (true);
CREATE POLICY "Room Bookings access" ON public.room_bookings FOR ALL USING (true);

-- Medical Security (from migration files)
CREATE POLICY "Medical access policy" on public.medical_requests for all using (
    (select access_medical from public.profiles where id = auth.uid()) = true
    or (select role from public.profiles where id = auth.uid()) = 'admin'
) with check (
    (select access_medical from public.profiles where id = auth.uid()) = true
    or (select role from public.profiles where id = auth.uid()) = 'admin'
);
CREATE POLICY "Procedures access policy" on public.medical_procedures for all using (true) with check (true);
CREATE POLICY "Materials access policy" on public.medical_materials for all using (true) with check (true);
CREATE POLICY "Attachments access policy" on public.medical_attachments for all using (true) with check (true);

-- Audit security
CREATE POLICY "Audit admin only" ON public.audit_logs FOR SELECT USING (
    (select role from public.profiles where id = auth.uid()) = 'admin'
);
