-- Create table for Room Bookings
create table public.room_bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  start_time time not null,
  end_time time not null,
  title text not null,
  description text
);

-- Enable Row Level Security (RLS)
alter table public.room_bookings enable row level security;

-- Create policy to allow all operations
create policy "Allow all operations for room_bookings" on public.room_bookings for all using (true) with check (true);
