-- 1. Adicionar colunas de data na tabela de Tarefas
alter table public.tasks 
add column if not exists start_date date,
add column if not exists deadline date;

-- 2. Criar tabela de Subtarefas
create table if not exists public.subtasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  task_id bigint references public.tasks(id) on delete cascade not null,
  title text not null,
  status text check (status in ('pending', 'done')) default 'pending'
);

-- 3. Habilitar RLS para subtarefas
alter table public.subtasks enable row level security;

do $$ 
begin
    if not exists (select 1 from pg_policies where tablename = 'subtasks' and policyname = 'Allow all operations for subtasks') then
        create policy "Allow all operations for subtasks" on public.subtasks for all using (true) with check (true);
    end if;
end $$;
