-- 1. Main Table for Medical Board Requests
create table if not exists public.medical_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  requisicao text unique not null,
  
  -- Beneficiary data (frozen at time of request)
  ben_nome text not null,
  ben_cpf text not null,
  ben_email text,
  ben_sexo text,
  ben_nascimento date,
  ben_telefone text,
  ben_estado text,
  ben_cidade text,
  
  -- Auditor data
  aud_nome text not null,
  aud_estado text,
  aud_crm text not null,
  aud_data date,
  
  -- Assistant data
  ass_nome text not null,
  ass_crm text not null,
  ass_email text,
  ass_telefone text,
  ass_endereco text,
  ass_especialidade text,
  
  -- Divergence info
  div_especialidade text,
  div_motivos text[], -- array of text
  
  situacao text not null default 'Aguardando Análise',
  prazo_ans date,
  
  -- Document tracking (JSONB for flexibility on internal state)
  documentos_internos jsonb default '{
    "aberturaBeneficiario": [],
    "aberturaFechamentoMedica": [],
    "desempatador": [],
    "parecerFinal": [],
    "emailConfirmacaoMedico": [],
    "beneficiarioAberturaFechamento": [],
    "confirmacaoRecebimento": []
  }'::jsonb
);

-- 2. Procedures Table
create table if not exists public.medical_procedures (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  codigo text,
  descricao text not null,
  qtd_solicitada integer default 1,
  qtd_autorizada integer default 0,
  justificativa text
);

-- 3. Materials / OPME Table
create table if not exists public.medical_materials (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  descricao text not null,
  qtd_solicitada integer default 1,
  qtd_autorizada integer default 0,
  justificativa text
);

-- 4. General Attachments (Manual uploads from step 5)
create table if not exists public.medical_attachments (
  id bigint generated by default as identity primary key,
  request_id bigint references public.medical_requests(id) on delete cascade not null,
  file_name text not null,
  file_path text not null,
  created_at timestamp with time zone default now()
);

-- 5. Add permission to profiles
do $$ 
begin
    if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'access_medical') then
        alter table public.profiles add column access_medical boolean default false;
    end if;
end $$;

-- Enable RLS for all tables
alter table public.medical_requests enable row level security;
alter table public.medical_procedures enable row level security;
alter table public.medical_materials enable row level security;
alter table public.medical_attachments enable row level security;

-- Policies (Simplified for the Hub)
do $$ 
begin
    -- Requests policy
    if not exists (select 1 from pg_policies where tablename = 'medical_requests' and policyname = 'Medical access policy') then
        create policy "Medical access policy" on public.medical_requests for all using (
            (select access_medical from public.profiles where id = auth.uid()) = true
            or (select role from public.profiles where id = auth.uid()) = 'admin'
        );
    end if;

    -- Procedure policy (inherits from request check via subquery or similar, keeping it simple here)
    if not exists (select 1 from pg_policies where tablename = 'medical_procedures' and policyname = 'Procedures access policy') then
        create policy "Procedures access policy" on public.medical_procedures for all using (true) with check (true);
    end if;
    
    if not exists (select 1 from pg_policies where tablename = 'medical_materials' and policyname = 'Materials access policy') then
        create policy "Materials access policy" on public.medical_materials for all using (true) with check (true);
    end if;

    if not exists (select 1 from pg_policies where tablename = 'medical_attachments' and policyname = 'Attachments access policy') then
        create policy "Attachments access policy" on public.medical_attachments for all using (true) with check (true);
    end if;
end $$;
