-- Create table for Projects
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  status text check (status in ('pending', 'progress', 'done', 'blocked')) default 'pending',
  priority text check (priority in ('low', 'medium', 'high')) default 'medium',
  deadline date
);

-- Create table for Tasks
create table public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references public.projects(id) on delete cascade not null,
  title text not null,
  status text check (status in ('pending', 'done')) default 'pending'
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.projects enable row level security;
alter table public.tasks enable row level security;

-- Create policies to allow all operations (since no auth is implemented yet)
-- WARNING: For production, you should implement proper authentication and policies.
create policy "Allow all operations for projects" on public.projects for all using (true) with check (true);
create policy "Allow all operations for tasks" on public.tasks for all using (true) with check (true);
