-- Create table for Projects
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  status text check (status in ('pending', 'progress', 'done', 'blocked')) default 'pending',
  priority text check (priority in ('low', 'medium', 'high')) default 'medium',
  deadline date
);

-- Create table for Tasks
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references public.projects(id) on delete cascade not null,
  title text not null,
  status text check (status in ('pending', 'done')) default 'pending'
);

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;
alter table public.tasks enable row level security;

-- Create policies to allow all operations (idempotent)
do $$ 
begin
    if not exists (select 1 from pg_policies where tablename = 'projects' and policyname = 'Allow all operations for projects') then
        create policy "Allow all operations for projects" on public.projects for all using (true) with check (true);
    end if;

    if not exists (select 1 from pg_policies where tablename = 'tasks' and policyname = 'Allow all operations for tasks') then
        create policy "Allow all operations for tasks" on public.tasks for all using (true) with check (true);
    end if;
end $$;
